
name: Workflow Simple Bonjour

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet de lancer manuellement le workflow

jobs:
  display-message:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Afficher un message
        run: echo "Bonjour, Workflow !"
