name: Génération PDF Bonjour

on:
  workflow_dispatch: # Permet de lancer manuellement le workflow

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install fpdf

      - name: Générer le fichier PDF
        run: |
          python -c "from fpdf import FPDF; pdf = FPDF(); pdf.add_page(); pdf.set_font('Arial', size=14); pdf.cell(190, 10, txt='Bonjour', ln=True); pdf.output('bonjour.pdf')"

      - name: Téléverser le PDF comme artefact
        uses: actions/upload-artifact@v3
        with:
          name: bonjour-pdf
          path: bonjour.pdf
